spring:
  application:
    name: spring-cloud-producer


server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8000/eureka/


#开启hystrix
feign:
  hystrix:
    enabled: true



hystrix:
  command:
    default:
      execution:
        timeout:
          enabled:  true
        isolation:
           thread:
             timeoutInMilliseconds: 9000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000